# Generated by Django 3.0 on 2021-04-05 13:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('activity_log', '0006_auto_20190816_1641'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitylog',
            name='user_id',
        ),
        migrations.AddField(
            model_name='activitylog',
            name='username',
            field=models.CharField(default='', max_length=256, verbose_name='user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
